console.log(false == "")
console.log(false == [])
console.log(false == {})
console.log("" == 0)//true
console.log("" == [])//true
console.log("" == {})//false
console.log(0 == [])//true
console.log(0 == {})//false
console.log(0 == null)//false